enum {
        FTFA_FSEC_SEC_UNSECURE = 2,
        FTFA_FSEC_SEC_SECURE = 3
};

enum {
        FTFA_FSEC_FSLACC_DENY = 1,
        FTFA_FSEC_FSLACC_GRANT = 3
};

enum {
        FTFA_FSEC_MEEN_DISABLE = 2,
        FTFA_FSEC_MEEN_ENABLE = 3
};

enum {
        FTFA_FSEC_KEYEN_DISABLE = 1,
        FTFA_FSEC_KEYEN_ENABLE = 2
};

enum FTFA_FCMD {
        FTFA_FCMD_READ_1s_SECTION = 0x01,
        FTFA_FCMD_PROGRAM_CHECK = 0x02,
        FTFA_FCMD_READ_RESOURCE = 0x03,
        FTFA_FCMD_PROGRAM_LONGWORD = 0x06,
        FTFA_FCMD_ERASE_SECTOR = 0x09,
        FTFA_FCMD_READ_1s_ALL_BLOCKS = 0x40,
        FTFA_FCMD_READ_ONCE = 0x41,
        FTFA_FCMD_PROGRAM_ONCE = 0x43,
        FTFA_FCMD_ERASE_ALL_BLOCKS = 0x44,
        FTFA_FCMD_VERIFY_KEY = 0x45,
};

enum FTFA_MARGIN_CHOICE {
        FTFA_MARGIN_NORMAL = 0x00,
        FTFA_MARGIN_USER = 0x01,
        FTFA_MARGIN_FACTORY = 0x02
};
