enum FTFE_FCMD {
        FTFE_FCMD_READ_1s_BLOCK = 0x00,
        FTFE_FCMD_READ_1s_SECTION = 0x01,
        FTFE_FCMD_PROGRAM_CHECK = 0x02,
        FTFE_FCMD_READ_RESOURCE = 0x03,
        FTFE_FCMD_PROGRAM_PHRASE = 0x07,
        FTFE_FCMD_ERASE_BLOCK = 0x08,
        FTFE_FCMD_ERASE_SECTOR = 0x09,
        FTFE_FCMD_PROGRAM_SECTION = 0x0b,
        FTFE_FCMD_READ_1s_ALL_BLOCKS = 0x40,
        FTFE_FCMD_READ_ONCE = 0x41,
        FTFE_FCMD_PROGRAM_ONCE = 0x43,
        FTFE_FCMD_ERASE_ALL_BLOCKS = 0x44,
        FTFE_FCMD_VERIFY_KEY = 0x45,
        FTFE_FCMD_SWAP_CONTROL = 0x46,
};

enum FTFE_MARGIN_CHOICE {
        FTFE_MARGIN_NORMAL = 0x00,
        FTFE_MARGIN_USER = 0x01,
        FTFE_MARGIN_FACTORY = 0x02
};

extern char FlexRAM[];
