enum {
        FTFL_FSEC_SEC_UNSECURE = 2,
        FTFL_FSEC_SEC_SECURE = 3
};

enum {
        FTFL_FSEC_FSLACC_DENY = 1,
        FTFL_FSEC_FSLACC_GRANT = 3
};

enum {
        FTFL_FSEC_MEEN_DISABLE = 2,
        FTFL_FSEC_MEEN_ENABLE = 3
};

enum {
        FTFL_FSEC_KEYEN_DISABLE = 1,
        FTFL_FSEC_KEYEN_ENABLE = 2
};

enum FTFL_FCMD {
        FTFL_FCMD_READ_1s_BLOCK = 0x00,
        FTFL_FCMD_READ_1s_SECTION = 0x01,
        FTFL_FCMD_PROGRAM_CHECK = 0x02,
        FTFL_FCMD_READ_RESOURCE = 0x03,
        FTFL_FCMD_PROGRAM_LONGWORD = 0x06,
        FTFL_FCMD_ERASE_BLOCK = 0x08,
        FTFL_FCMD_ERASE_SECTOR = 0x09,
        FTFL_FCMD_PROGRAM_SECTION = 0x0b,
        FTFL_FCMD_READ_1s_ALL_BLOCKS = 0x40,
        FTFL_FCMD_READ_ONCE = 0x41,
        FTFL_FCMD_PROGRAM_ONCE = 0x43,
        FTFL_FCMD_ERASE_ALL_BLOCKS = 0x44,
        FTFL_FCMD_VERIFY_KEY = 0x45,
        FTFL_FCMD_PROGRAM_PARTITION = 0x80,
        FTFL_FCMD_SET_FLEXRAM = 0x81
};

enum FTFL_MARGIN_CHOICE {
        FTFL_MARGIN_NORMAL = 0x00,
        FTFL_MARGIN_USER = 0x01,
        FTFL_MARGIN_FACTORY = 0x02
};

enum FTFL_FLEXNVM_PARTITION {
        FTFL_FLEXNVM_DATA_32_EEPROM_0 = 0xF0,
        FTFL_FLEXNVM_DATA_24_EEPROM_8 = 0xF1,
        FTFL_FLEXNVM_DATA_16_EEPROM_16 = 0xF2,
        FTFL_FLEXNVM_DATA_8_EEPROM_24 = 0xF9,
        FTFL_FLEXNVM_DATA_0_EEPROM_32 = 0xF3
};

enum FTFL_EEPROM_SIZE {
        FTFL_EEPROM_SIZE_0 = 0x3f,
        FTFL_EEPROM_SIZE_32 = 0x39,
        FTFL_EEPROM_SIZE_64 = 0x38,
        FTFL_EEPROM_SIZE_128 = 0x37,
        FTFL_EEPROM_SIZE_256 = 0x36,
        FTFL_EEPROM_SIZE_512 = 0x35,
        FTFL_EEPROM_SIZE_1024 = 0x34,
        FTFL_EEPROM_SIZE_2048 = 0x33
};

enum FTFL_FLEXRAM_FUNCTION {
        FTFL_FLEXRAM_EEPROM = 0x00,
        FTFL_FLEXRAM_RAM = 0xff
};

extern char FlexRAM[];
