#include <soc/cortex-m/soc.h>

#include <soc/kinetis/periph/ftfl.h>
#include <soc/kinetis/periph/usbotg.h>
#include <soc/kinetis/periph/sim.h>
#include <soc/kinetis/periph/mcg.h>
#include <soc/kinetis/periph/rcm.h>
#include <soc/kinetis/periph/port.h>
#include <soc/kinetis/periph/gpio.h>
#include <soc/kinetis/periph/pmc.h>
#include <soc/kinetis/periph/adc.h>
#include <soc/kinetis/periph/spi.h>
#include <soc/kinetis/periph/lptmr.h>
#include <soc/kinetis/periph/ftm.h>
#include <soc/kinetis/periph/i2c.h>
#include <soc/kinetis/periph/pit.h>
#include <soc/kinetis/periph/tsi.h>
#include <soc/kinetis/periph/uart.h>
#include <soc/kinetis/periph/rtc.h>
#include <soc/kinetis/periph/crc.h>
#include <soc/kinetis/periph/llwu.h>
#include <soc/kinetis/periph/smc.h>
#include <soc/kinetis/periph/vbat.h>
#include <soc/kinetis/periph/vref.h>
#include <soc/kinetis/periph/cmp.h>

#include <soc/kinetis/adc.h>
#include <soc/kinetis/crc.h>
#include <soc/kinetis/flash.h>
#include <soc/kinetis/ftm.h>
#include <soc/kinetis/i2c.h>
#include <soc/kinetis/onboard-led.h>
#include <soc/kinetis/pin.h>
#include <soc/kinetis/pin_change.h>
#include <soc/kinetis/gpio.h>
#include <soc/kinetis/pit.h>
#include <soc/kinetis/rtc.h>
#include <soc/kinetis/spi.h>
#include <soc/kinetis/stdio.h>
#include <soc/kinetis/timeout.h>
#include <soc/kinetis/uart.h>
